### ISSUE TITLE
Update touch disabler sysfs interface (separate ts/tk control)

### ISSUE THREAD

**Issue by vzvikaramba** [Galaxy-MSM8916/android_kernel_samsung_msm8916#11]
Update with reworked sysfs interface resembling this:

/sys/class
└── touch_disabler
  ├── touch_key
  │   ├── enabled
  │   └── mode
  └── touch_panel
       ├── enabled
       └── mode

For separate control of tk/ts.

**Comment by vlw** [comment]
I didn't guess that it is good idea

**Comment by vlw** [comment]
/sys/class/touch_disabler
├── touch_key
│ ├── enabled
│ └── mode
├── touch_panel
│ ├── enabled
│ └── mode
├── enabled
└── mode

This will better. But are we need separate control? I guess we're need only separated TK disablement. For example:
/sys/class/touch_disabler
├── touch_key
│ └── force_disabled
├── enabled
└── mode

force_disabled is false by default.
If force_disabled status is true then buttons willn't enabled with common "enabled" trigger

this needed for key_disabler cmhw

**Comment by minz1** [comment]
@vlw The original model of the sysfs interface seems better to me

**Comment by vzvikaramba** [comment]
This is what my diagram was supposed to look like:

/sys/class/touch_disabler
  ├── touch_key
  │   ├── enabled
  │   └── mode
  └── touch_panel
       ├── enabled
       └── mode

But we can go with whichever one you guys prefer.

**Comment by vzvikaramba** [comment]
The one I intended is much more difficult to implement, an easier one would be:

/sys/class/touch_key
   ├── enabled
   └── mode

/sys/class/touch_panel
   ├── enabled
   └── mode

**Comment by minz1** [comment]
That one seems good to me

**Comment by vzvikaramba** [comment]
The latter? So are we all agreed then?

**Comment by vlw** [comment]
@vince2678 It will harder to implement to the keydisabler

**Comment by vzvikaramba** [comment]
@vlw you mean the cmhw class, or the touch driver?

In either case, it is actually much easier to implement than the first one I had proposed.

**Comment by vlw** [comment]
@vince2678 I mean cmhw class

**Comment by vzvikaramba** [comment]
@vlw, should still be straightforward.

**Comment by vzvikaramba** [comment]
Done.

See:

https://github.com/Galaxy-MSM8916/android_device_samsung_msm8916-common/commit/55527ece0df1bb5941f741071f4d1ea58a0a22e7

As well as the kernel.

**Comment by vzvikaramba** [comment]
https://github.com/Galaxy-MSM8916/android_device_samsung_msm8916-common/commit/55527ece0df1bb5941f741071f4d1ea58a0a22e7
