### ISSUE TITLE
Cannot open Google Play Store

### ISSUE THREAD

**Issue by MidnightTempest** [Galaxy-MSM8916/android_kernel_samsung_msm8916#14]
Just installed your ROM on a SM-J510FN and i can't open Google Play Store or sign in to my google account

**Comment by minz1** [comment]
@MidnightTempest Did you flash gapps?

**Comment by MidnightTempest** [comment]
Yeah, I just remembered :D. Haven't installed a ROM in a while, please excuse my retardness
