### ISSUE TITLE
Add BFQ sched

### ISSUE THREAD

**Issue by vzvikaramba** [Galaxy-MSM8916/android_kernel_samsung_msm8916#3]

**Comment by minz1** [comment]
https://github.com/Galaxy-MSM8916/android_kernel_samsung_msm8916/commit/7ff93385dcc6b2800b8a5028f8000aa732fb72dd
https://github.com/Galaxy-MSM8916/android_kernel_samsung_msm8916/commit/de9003113ba13d247ad6960a190ab0b7d0535a56
https://github.com/Galaxy-MSM8916/android_kernel_samsung_msm8916/commit/d6cab26d39c59e75dc1f264d6d2f61c500162414
https://github.com/Galaxy-MSM8916/android_kernel_samsung_msm8916/commit/fd91f20f657aa3eb75b714b809d511f44284e290
https://github.com/Galaxy-MSM8916/android_kernel_samsung_msm8916/commit/ce793bd96e7d70f056e8a0c145aa15ec1e4dd59e

Should be taken care of here.

**Comment by vzvikaramba** [comment]
Merged on gerrit. Thanks.
