### ISSUE TITLE
Define common interface for touch disablement

### ISSUE THREAD

**Issue by vzvikaramba** [Galaxy-MSM8916/android_kernel_samsung_msm8916#4]
* Define common interface (header, maybe function pointer(s) in struct or just function signatures) for touch enablement/disablement functions in touch drivers.
* Modify mdss screen blank/unblank function to call said function

 Will need to modify all touch drivers.

**Comment by vlw** [comment]
Common interface is ready 24a7b5804bd2337bd325f537f849f2cfda937883

**Comment by vzvikaramba** [comment]
The implementation above is implemented in more code than is needed, I'm doing another version of the thing on the cm-14.1-touch-2 branch.

**Comment by vlw** [comment]
b6dce37bc96a28f13de3573dea6fd3e9ead84d3e

**Comment by vzvikaramba** [comment]
Done.
