### ISSUE TITLE
We're need to add vibration intensity control

### ISSUE THREAD

**Issue by vlw** [Galaxy-MSM8916/android_kernel_samsung_msm8916#5]
LineageOS is support to switching vibration intensity in settings, kernel must have this feature.

 https://github.com/vlw/android_kernel_samsung_msm8916_A3/commit/d7f34e314d2671e9e26f0a0545f6b705772d5386

**Comment by vzvikaramba** [comment]
Doesn't this need a corresponding cmhw class to work?

**Comment by vzvikaramba** [comment]
Those drivers are from the old LP samsung kernels, the could require some modifications to work with the new vib drivers in the MM kernel.

**Comment by vlw** [comment]
cmhw class isn't needed, just need to add this sysfs class

**Comment by vlw** [comment]
@vlw lol

**Comment by deadman96385** [comment]
@vlw Well the cmhw adds the fuctionailty to the system so its actually useful

**Comment by vzvikaramba** [comment]
@deadman96385 Yeah, so I guess if the class isn't there in  hardware/cyanogen then one will need to be made

**Comment by deadman96385** [comment]
@vince2678 Should be one in hardware/samsung that should either work out of the box or with a little modification

**Comment by vzvikaramba** [comment]
@deadman96385 Ok. I'll do the kernel side stuff for the vib drivers, can someone else check the cmhw stuff when that's done? We already inherit hardware/samsung/cmhw and hardware/cyanogen/cmhw, so if it's already there then the kernel stuff is as much as we'll need to do

**Comment by vlw** [comment]
@deadman96385 There is NOT needed any modification of tree, just add few sysfs controls, Lineage will automatically add intensity control to the settings

**Comment by deadman96385** [comment]
@vlw That is due to us already including hardware/samsung for cmhw so i guess that cmhw vibration one works

**Comment by vlw** [comment]
Ready f22be9ce7e6aee79d4ce5a22d2b398bc2986e919
Now we're need to push it to the Gerrit

**Comment by vzvikaramba** [comment]
After the chown/chmod, does this work fine now?

**Comment by vlw** [comment]
@vince2678

**Comment by vzvikaramba** [comment]
Yeah, it works fine.

Closed.
