### ISSUE TITLE
Add MPDecision kernel module

### ISSUE THREAD

**Issue by vlw** [Galaxy-MSM8916/android_kernel_samsung_msm8916#8]
It is an msm-hotplug. We will get long baterry life and very smoothly work rom

**Comment by vzvikaramba** [comment]
@minz1? 

Personally, I'm not a fan of the idea of adding tweaks to the kernel. I'd rather the kernel stay as long to stock as possible. And I'm not sure the lineage people would accept that. 

You can go ahead and add it to a topic branch and we'll discuss further.

**Comment by minz1** [comment]
@vince2678 I'm going to have to agree with this sentiment
